[package]
name = "typewheel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.108"
serde_test = "1.0.176"
