name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg ci

jobs:
  build_and_test:
    name: Typewheel - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
    - run: cargo build --verbose
    - run: RUSTFLAGS="-Dwarnings" cargo clippy --verbose
    - run: cargo test --verbose