on: push
name: Clippy check

env:
  RUSTFLAGS: "-Dwarnings --cfg ci"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features
